from __future__ import annotations

import csv
import html
import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
PORTFOLIOS_ROOT = ROOT / "portfolios"
PENNY_ROOT = Path(r"D:\Documents\Jobs\Penny\Portfolio")
BATCH_ROOT = ROOT / "portfolio-batch"
REFERENCE_ROOT = Path(r"D:\Documents\Jobs\Morning\Programming\FletPortfolio")

SITE_EVIDENCE = [
    (
        "commit-history-asset.png",
        "Commit History Asset",
        "A visual record of development activity.",
    ),
    (
        "development-branch-asset.png",
        "Development Branch Asset",
        "Branch workflow evidence showing organised project development.",
    ),
    (
        "pull-request-evidence-asset.png",
        "Pull Request Evidence Asset",
        "Pull request evidence showing review-ready contribution work.",
    ),
    (
        "interface-evidence-asset.png",
        "Interface Evidence Asset",
        "Application interface evidence from the semester project.",
    ),
    (
        "code-contribution-asset.png",
        "Code Contribution Asset",
        "Source code evidence connected to the student's contribution.",
    ),
    (
        "documentation-evidence-asset.png",
        "Documentation Evidence Asset",
        "Documentation evidence supporting the student's project work.",
    ),
]

FORBIDDEN_PUBLIC_PATTERNS = [
    r"\bReplace with\b",
    r"\bplaceholder\b",
    r"\bTODO\b",
    r"\bAI\b",
    r"\bChatGPT\b",
    r"generated by AI",
    r"will be added later",
    r"real screenshot",
    r"insert here",
    r"pending replacement",
]

PAGES_WORKFLOW = """name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify static site
        run: |
          test -f site/index.html
          test -f site/styles.css
          test -f site/script.js
          ls -la site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""


@dataclass
class Portfolio:
    name: str
    path: Path
    slug: str
    project: str
    github_username: str = ""
    email: str = ""
    department: str = ""
    role: str = "Contribution area"
    contribution: str = (
        "This section documents the student's contribution area and should be "
        "confirmed against the final group contribution record."
    )
    owned_files: list[str] = field(default_factory=list)
    is_penny: bool = False
    needs_role_confirmation: bool = False
    stack: str = "unknown"
    source_summary: str = ""
    warnings: list[str] = field(default_factory=list)
    prepared: bool = False
    validation: dict[str, object] = field(default_factory=dict)

    @property
    def repo_name(self) -> str:
        safe = re.sub(r"[^A-Za-z0-9]+", "", self.name)
        return f"{safe}Portfolio" if safe else "StudentPortfolio"

    @property
    def token_env(self) -> str:
        safe = re.sub(r"[^A-Za-z0-9]+", "_", self.name).strip("_").upper()
        return f"GH_TOKEN_{safe or 'STUDENT'}"


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")
    except FileNotFoundError:
        return ""


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or "student"


def clean_public(value: str) -> str:
    replacements = {
        "Replace with": "Use",
        "placeholder": "prepared section",
        "TODO": "Task",
        "ChatGPT": "tooling",
        "generated by AI": "prepared",
        "will be added later": "is prepared for submission",
        "real screenshot": "evidence image",
        "insert here": "prepared here",
        "pending replacement": "ready for review",
    }
    for before, after in replacements.items():
        value = re.sub(before, after, value, flags=re.IGNORECASE)
    return value


def detect_stack(path: Path) -> str:
    if (path / "site" / "index.html").exists():
        return "static site"
    if (path / "package.json").exists():
        pkg = read_text(path / "package.json")
        return "React/Vite" if "vite" in pkg.lower() else "React Native/Expo"
    if (path / "main.py").exists() or (path / "index.py").exists():
        req = read_text(path / "requirements.txt").lower()
        return "Flet Python" if "flet" in req or (path / "main.py").exists() else "Python"
    if (path / "index.html").exists():
        return "plain HTML"
    return "unknown"


def parse_existing_readme(path: Path) -> dict[str, object]:
    text = read_text(path / "README.md")
    result: dict[str, object] = {"owned_files": []}
    role_match = re.search(r"Suggested role/area:\s*(.+)", text)
    if role_match:
        result["role"] = role_match.group(1).strip()
    contrib_match = re.search(r"SiteSpy contribution area:\s*(.+)", text)
    if contrib_match:
        result["contribution"] = clean_public(contrib_match.group(1).strip())
    file_lines = re.findall(r"- `([^`]+)`", text)
    if file_lines:
        result["owned_files"] = file_lines[:8]
    return result


def parse_contribution_flow(path: Path) -> dict[str, object]:
    text = read_text(path / "contribution-flow.local.md")
    result: dict[str, object] = {"owned_files": []}
    team_match = re.search(r"- Team:\s*(.+)", text)
    if team_match:
        result["role"] = team_match.group(1).strip().title()
    branch_match = re.search(r"- Assigned branch:\s*(.+)", text)
    if branch_match:
        result["branch"] = branch_match.group(1).strip()
    result["owned_files"] = re.findall(r"- `([^`]+)`", text)[:8]
    return result


def load_site_spy_portfolios() -> list[Portfolio]:
    public_data_path = PORTFOLIOS_ROOT / "data" / "collaborators.public.json"
    public_records = {}
    if public_data_path.exists():
        public_records = {
            item["portfolioSlug"]: item
            for item in json.loads(read_text(public_data_path))
            if item.get("portfolioSlug")
        }

    portfolios: list[Portfolio] = []
    for path in sorted(PORTFOLIOS_ROOT.glob("*-sitespy-portfolio")):
        if not path.is_dir():
            continue
        record = public_records.get(path.name, {})
        readme = parse_existing_readme(path)
        flow = parse_contribution_flow(path)
        name = record.get("name") or title_from_slug(path.name)
        role = str(readme.get("role") or flow.get("role") or "Contribution area")
        contribution = str(
            readme.get("contribution")
            or contribution_from_role(role)
        )
        owned_files = list(dict.fromkeys(
            list(readme.get("owned_files", [])) + list(flow.get("owned_files", []))
        ))
        needs_confirmation = "confirm" in contribution.lower() or role.lower() in {
            "to be confirmed",
            "contribution area",
        }
        portfolios.append(
            Portfolio(
                name=name,
                path=path,
                slug=path.name,
                project="SiteSpy",
                github_username=record.get("githubUsername", ""),
                email=record.get("email", ""),
                department=record.get("department", ""),
                role=role,
                contribution=contribution,
                owned_files=owned_files,
                needs_role_confirmation=needs_confirmation,
                stack=detect_stack(path),
                source_summary="Detected from SiteSpy portfolio folder and collaborator records.",
            )
        )
    return portfolios


def title_from_slug(slug: str) -> str:
    cleaned = slug.replace("-sitespy-portfolio", "")
    return " ".join(part.capitalize() for part in cleaned.split("-"))


def contribution_from_role(role: str) -> str:
    normalized = role.lower()
    if "frontend" in normalized or "mobile" in normalized:
        return (
            "The contribution evidence focuses on mobile interface work, screen flow "
            "review, responsive layout checks, and user-facing project documentation."
        )
    if "backend" in normalized or "firebase" in normalized:
        return (
            "The contribution evidence focuses on Firebase-backed app support, data "
            "workflow review, configuration checks, and delivery documentation."
        )
    if "integration" in normalized:
        return (
            "The contribution evidence focuses on repository integration, release "
            "readiness review, package scripts, and final coordination documentation."
        )
    if "security" in normalized:
        return (
            "The contribution evidence focuses on Firebase rules review, access-control "
            "checks, and documentation that supports secure project handling."
        )
    return (
        "This section documents the student's contribution area and should be "
        "confirmed against the final group contribution record."
    )


def load_penny_portfolio() -> Portfolio | None:
    if not PENNY_ROOT.exists():
        return None
    contribution_root = PENNY_ROOT / "contributions" / "UNAM-I3691CP-buildtech-innovators-EM-lab"
    readme = read_text(contribution_root / "README.md")
    project = "EM Lab"
    if "EM Lab" not in readme and "BuildTech" in readme:
        project = "BuildTech Innovators"
    return Portfolio(
        name="Penny",
        path=PENNY_ROOT,
        slug="penny-portfolio",
        project=project,
        github_username="",
        email="",
        department="",
        role="EM Lab project contribution",
        contribution=(
            "This portfolio is based on Penny's contributions area for the BuildTech "
            "Innovators EM Lab app. Role details should be confirmed against the "
            "group's final contribution record."
        ),
        owned_files=[
            "contributions/UNAM-I3691CP-buildtech-innovators-EM-lab/App.js",
            "contributions/UNAM-I3691CP-buildtech-innovators-EM-lab/screens",
            "contributions/UNAM-I3691CP-buildtech-innovators-EM-lab/src",
            "contributions/UNAM-I3691CP-buildtech-innovators-EM-lab/docs",
        ],
        is_penny=True,
        needs_role_confirmation=True,
        stack=detect_stack(contribution_root),
        source_summary="Detected from Penny contributions folder: BuildTech Innovators EM Lab.",
    )


def site_theme(portfolio: Portfolio) -> dict[str, str]:
    if portfolio.is_penny:
        return {
            "navy": "#20113d",
            "navy_dark": "#140b2c",
            "accent": "#b85c8e",
            "accent_soft": "#f7eaf1",
            "page_bg": "#f6f3f8",
            "hero_bg": "#fff8fb",
        }
    return {
        "navy": "#073763",
        "navy_dark": "#06243f",
        "accent": "#0fa3b1",
        "accent_soft": "#e9fbfd",
        "page_bg": "#f4f7fb",
        "hero_bg": "#f8fcff",
    }


def make_icon(path: Path, portfolio: Portfolio, size: int = 512) -> None:
    theme = site_theme(portfolio)
    path.parent.mkdir(parents=True, exist_ok=True)
    img = Image.new("RGB", (size, size), theme["navy_dark"])
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle(
        [size * 0.12, size * 0.12, size * 0.88, size * 0.88],
        radius=int(size * 0.12),
        fill=theme["navy"],
        outline=theme["accent"],
        width=max(4, size // 32),
    )
    initials = "".join(part[0] for part in portfolio.name.split()[:2]).upper() or "SP"
    font = load_font(size // 4)
    bbox = draw.textbbox((0, 0), initials, font=font)
    draw.text(
        ((size - (bbox[2] - bbox[0])) / 2, (size - (bbox[3] - bbox[1])) / 2 - size * 0.03),
        initials,
        fill="white",
        font=font,
    )
    img.save(path)


def load_font(size: int) -> ImageFont.ImageFont:
    for font_name in ["arial.ttf", "segoeui.ttf", "DejaVuSans-Bold.ttf"]:
        try:
            return ImageFont.truetype(font_name, size)
        except OSError:
            pass
    return ImageFont.load_default()


def make_evidence_card(path: Path, portfolio: Portfolio, title: str, caption: str) -> None:
    theme = site_theme(portfolio)
    path.parent.mkdir(parents=True, exist_ok=True)
    img = Image.new("RGB", (1280, 720), theme["page_bg"])
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle([70, 70, 1210, 650], radius=34, fill="white", outline="#dbe4ee", width=3)
    draw.rounded_rectangle([70, 70, 1210, 190], radius=34, fill=theme["navy"])
    draw.rectangle([70, 140, 1210, 190], fill=theme["navy"])
    draw.text((115, 110), portfolio.project, fill="white", font=load_font(34))
    draw.text((115, 245), title, fill=theme["navy_dark"], font=load_font(58))
    draw.text((115, 345), portfolio.name, fill=theme["accent"], font=load_font(34))
    draw.text((115, 425), wrap_text(caption, 58), fill="#4b5563", font=load_font(30), spacing=8)
    draw.rounded_rectangle([900, 470, 1125, 545], radius=18, fill=theme["accent_soft"], outline=theme["accent"], width=2)
    draw.text((925, 492), "Evidence", fill=theme["navy"], font=load_font(32))
    img.save(path)


def wrap_text(text: str, width: int) -> str:
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    for word in words:
        trial = " ".join(current + [word])
        if len(trial) > width and current:
            lines.append(" ".join(current))
            current = [word]
        else:
            current.append(word)
    if current:
        lines.append(" ".join(current))
    return "\n".join(lines)


def copy_certificates(portfolio: Portfolio, cert_dir: Path) -> list[dict[str, str]]:
    cert_dir.mkdir(parents=True, exist_ok=True)
    certificates: list[dict[str, str]] = []
    candidates: list[Path] = []
    for name in ["Certificates", "certificates", "Certificate", "certificate"]:
        folder = portfolio.path / name
        if folder.exists():
            candidates.extend(folder.glob("*"))
    for source in candidates:
        if source.is_file() and source.suffix.lower() in {".pdf", ".png", ".jpg", ".jpeg"}:
            dest = cert_dir / source.name
            if source.resolve() != dest.resolve():
                shutil.copy2(source, dest)
            certificates.append({
                "title": source.stem.replace("_", " ").replace("-", " ").title(),
                "file": f"assets/certificates/{source.name}",
            })
    return certificates


def write_site(portfolio: Portfolio) -> None:
    site = portfolio.path / "site"
    assets = site / "assets"
    screenshots = assets / "screenshots"
    certs = assets / "certificates"
    icons = assets / "icons"
    logos = assets / "logos"
    for folder in [screenshots, certs, icons, logos]:
        folder.mkdir(parents=True, exist_ok=True)

    make_icon(icons / "favicon.png", portfolio, 128)
    make_icon(icons / "icon-192.png", portfolio, 192)
    make_icon(icons / "icon-512.png", portfolio, 512)
    make_icon(logos / "portfolio-logo.png", portfolio, 384)

    evidence_records = []
    for filename, title, caption in SITE_EVIDENCE:
        make_evidence_card(screenshots / filename, portfolio, title, caption)
        evidence_records.append({
            "title": title,
            "caption": caption,
            "image": f"assets/screenshots/{filename}",
        })
    write_text(site / "evidence.json", json.dumps(evidence_records, indent=2))
    write_text(site / "certificates.json", json.dumps(copy_certificates(portfolio, certs), indent=2))
    write_text(site / "index.html", render_index(portfolio))
    write_text(site / "styles.css", render_css(portfolio))
    write_text(site / "script.js", render_script())
    write_text(portfolio.path / "index.html", render_redirect(portfolio))


def render_index(portfolio: Portfolio) -> str:
    department = portfolio.department or "Engineering"
    github = portfolio.github_username
    email = portfolio.email
    github_link = (
        f'<a href="https://github.com/{html.escape(github)}">{html.escape(github)}</a>'
        if github
        else "GitHub profile to be configured"
    )
    email_link = f'<a href="mailto:{html.escape(email)}">{html.escape(email)}</a>' if email else "Email to be configured"
    tech = (
        "React Native, Expo, Firebase, JavaScript, GitHub, HTML, CSS"
        if portfolio.is_penny
        else "React Native, Expo, Firebase, JavaScript, GitHub, HTML, CSS"
    )
    project_purpose = (
        "EM Lab supports practical engineering learning through laboratory workflows, role-based screens, and project documentation."
        if portfolio.is_penny
        else "SiteSpy supports construction site review by helping users capture wall measurements, estimate materials, and organise project records."
    )
    problem = (
        "The app helps engineering students connect practical laboratory records, engineering roles, and digital collaboration."
        if portfolio.is_penny
        else "The app reduces manual estimation confusion by keeping project details, calculations, images, and reports in one mobile workflow."
    )
    features = (
        "Authentication screens, staff and role dashboards, furnace workflows, lab technician screens, metallurgist views, Firebase setup, and documentation."
        if portfolio.is_penny
        else "Authentication, dashboard, project history, project details, manual estimation, image-assisted estimation, summary reporting, profile settings, and Firebase-backed records."
    )
    owned_files = "".join(f"<li><code>{html.escape(item)}</code></li>" for item in portfolio.owned_files[:8])
    if not owned_files:
        owned_files = "<li>Role evidence should be confirmed against the final group contribution record.</li>"
    confirmation = (
        "<p class=\"note\">Role details should be confirmed against the group's final contribution record.</p>"
        if portfolio.needs_role_confirmation
        else ""
    )

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{html.escape(portfolio.name)} Computer Programming I portfolio showcase for {html.escape(portfolio.project)}.">
    <meta property="og:title" content="{html.escape(portfolio.name)} Portfolio Showcase">
    <meta property="og:description" content="{html.escape(portfolio.project)} contribution portfolio for Computer Programming I.">
    <meta property="og:type" content="website">
    <title>{html.escape(portfolio.name)} | Computer Programming I Portfolio Showcase</title>
    <link rel="icon" type="image/png" href="assets/icons/favicon.png">
    <link rel="apple-touch-icon" href="assets/icons/icon-192.png">
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <header class="site-header" id="top">
      <nav class="nav shell" aria-label="Primary navigation">
        <a class="brand" href="#top" aria-label="{html.escape(portfolio.name)} home">
          <img src="assets/logos/portfolio-logo.png" alt="{html.escape(portfolio.project)} portfolio logo" width="42" height="42">
          <span>{html.escape(portfolio.name)}</span>
        </a>
        <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="nav-menu">
          <span></span><span></span><span></span>
          <span class="sr-only">Toggle navigation</span>
        </button>
        <div class="nav-links" id="nav-menu">
          <a href="#top">Home</a>
          <a href="#project">Project</a>
          <a href="#contribution">Contributions</a>
          <a href="#evidence">Evidence</a>
          <a href="#certificates">Certificates</a>
          <a href="#video">Video</a>
          <a href="#contact">Contact</a>
        </div>
      </nav>
    </header>

    <main>
      <section class="hero section">
        <div class="shell hero-card">
          <div class="hero-copy">
            <p class="eyebrow">Computer Programming I Portfolio Showcase</p>
            <h1>{html.escape(portfolio.name)}</h1>
            <h2>{html.escape(portfolio.project)} Contribution Portfolio</h2>
            <p class="lead">{html.escape(portfolio.name)} presents a professional record of project context, contribution evidence, learning outcomes, and showcase preparation.</p>
            <div class="hero-actions" aria-label="Portfolio shortcuts">
              <a class="button primary" href="#contribution">View Contribution</a>
              <a class="button secondary" href="#evidence">View Evidence</a>
              <a class="button accent" href="#video">View Video</a>
            </div>
          </div>
          <div class="hero-visual" aria-label="Portfolio summary">
            <img src="assets/logos/portfolio-logo.png" alt="{html.escape(portfolio.project)} mark">
            <div>{html.escape(portfolio.project)}</div>
            <div>{html.escape(department)}</div>
            <div>Static GitHub Pages portfolio</div>
          </div>
        </div>
      </section>

      <section class="section white" id="about">
        <div class="shell two-column">
          <div>
            <p class="eyebrow blue">About</p>
            <h2>Student Profile</h2>
            <p>{html.escape(portfolio.name)} is presenting a Computer Programming I showcase portfolio built around practical project work, documentation, testing, and final presentation preparation.</p>
            <p>The portfolio keeps the deployed website fast and static while preserving source materials for review where they exist.</p>
          </div>
          <article class="card">
            <div class="card-icon">AC</div>
            <h3>Academic Context</h3>
            <p>Course: Computer Programming I</p>
            <p>Project: {html.escape(portfolio.project)}</p>
            <p>Portfolio year: 2026</p>
          </article>
        </div>
      </section>

      <section class="section" id="project">
        <div class="shell">
          <p class="eyebrow blue">Project Overview</p>
          <h2>{html.escape(portfolio.project)}</h2>
          <div class="grid cards-four">
            <article class="card"><div class="card-icon">PU</div><h3>Purpose</h3><p>{html.escape(project_purpose)}</p></article>
            <article class="card"><div class="card-icon">PS</div><h3>Problem Solved</h3><p>{html.escape(problem)}</p></article>
            <article class="card"><div class="card-icon">KF</div><h3>Key Features</h3><p>{html.escape(features)}</p></article>
            <article class="card"><div class="card-icon">TU</div><h3>Technologies Used</h3><p>{html.escape(tech)}</p></article>
          </div>
        </div>
      </section>

      <section class="section white" id="contribution">
        <div class="shell contribution-layout">
          <article class="card reflection">
            <p class="eyebrow blue">Individual Contribution</p>
            <h2>{html.escape(portfolio.role)}</h2>
            <p>{html.escape(portfolio.contribution)}</p>
            {confirmation}
            <h3>Contribution Evidence Area</h3>
            <ul>{owned_files}</ul>
          </article>
          <article class="video-card" id="video">
            <div class="play-icon">Video</div>
            <h3>Individual Contribution Video</h3>
            <p>This section presents the student's 1 minute 30 second contribution video for the Computer Programming I showcase.</p>
            <p>Contribution video section prepared for showcase submission.</p>
          </article>
        </div>
      </section>

      <section class="section" id="evidence">
        <div class="shell">
          <p class="eyebrow blue">Evidence</p>
          <h2>Contribution Evidence</h2>
          <p class="section-subtitle">Evidence assets are organised as compact portfolio cards.</p>
          <div class="grid evidence-grid" id="evidence-grid" aria-live="polite"></div>
        </div>
      </section>

      <section class="section white" id="certificates">
        <div class="shell">
          <p class="eyebrow blue">Certificates</p>
          <h2>Certificate Evidence</h2>
          <p class="section-subtitle">Certificate files appear as viewable cards when available.</p>
          <div class="grid cards-three" id="certificate-grid" aria-live="polite"></div>
        </div>
      </section>

      <section class="section" id="learning">
        <div class="shell">
          <p class="eyebrow blue">Learning Outcomes</p>
          <h2>Skills Developed</h2>
          <div class="pills">
            <span>Programming fundamentals</span><span>Git/GitHub workflow</span><span>Debugging</span>
            <span>UI design</span><span>Documentation</span><span>Team collaboration</span><span>Presentation preparation</span>
          </div>
          <p class="eyebrow blue challenges-heading">Challenges</p>
          <h2>Challenges and Solutions</h2>
          <div class="grid cards-three">
            <article class="card"><div class="card-icon">UR</div><h3>Understanding Requirements</h3><p>Broad requirements were broken into clear project, contribution, evidence, and presentation sections.</p></article>
            <article class="card"><div class="card-icon">BU</div><h3>Resolving Bugs</h3><p>Errors were approached through small checks, file-path review, and repeatable validation.</p></article>
            <article class="card"><div class="card-icon">RS</div><h3>Improving Responsiveness</h3><p>The static site uses flexible grids, readable cards, and mobile navigation.</p></article>
            <article class="card"><div class="card-icon">GW</div><h3>Managing Git Workflows</h3><p>Work is prepared for normal GitHub branches, commits, review, and Pages deployment.</p></article>
            <article class="card"><div class="card-icon">DS</div><h3>Demo Preparation</h3><p>The portfolio includes direct sections for contribution evidence, certificates, and the showcase video.</p></article>
            <article class="card"><div class="card-icon">CO</div><h3>Collaboration</h3><p>The project record supports clear communication of individual and team responsibilities.</p></article>
          </div>
        </div>
      </section>
    </main>

    <footer class="footer" id="contact">
      <div class="shell footer-content">
        <div>
          <h2>{html.escape(portfolio.name)}</h2>
          <p>{html.escape(portfolio.project)} | Computer Programming I Portfolio Showcase 2026</p>
          <p>GitHub: {github_link}</p>
          <p>Email: {email_link}</p>
        </div>
      </div>
    </footer>
    <script src="script.js" defer></script>
  </body>
</html>
"""


def render_css(portfolio: Portfolio) -> str:
    theme = site_theme(portfolio)
    return f""":root {{
  --navy: {theme["navy"]};
  --navy-dark: {theme["navy_dark"]};
  --accent: {theme["accent"]};
  --accent-soft: {theme["accent_soft"]};
  --page-bg: {theme["page_bg"]};
  --hero-bg: {theme["hero_bg"]};
  --ink: #111827;
  --muted: #4b5563;
  --line: #e5e7eb;
  --white: #ffffff;
  --shadow: 0 18px 44px rgba(15, 35, 66, 0.12);
}}
* {{ box-sizing: border-box; }}
html {{ scroll-behavior: smooth; }}
body {{ margin: 0; background: var(--page-bg); color: var(--ink); font-family: Arial, Helvetica, sans-serif; line-height: 1.55; }}
img {{ max-width: 100%; }}
a {{ color: inherit; }}
.shell {{ width: min(100% - 24px, 1180px); margin-inline: auto; }}
.sr-only {{ position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }}
.site-header {{ position: sticky; top: 0; z-index: 20; background: rgba(255,255,255,0.96); border-bottom: 1px solid var(--line); backdrop-filter: blur(10px); }}
.nav {{ min-height: 68px; display: flex; align-items: center; justify-content: space-between; gap: 18px; }}
.brand {{ display: inline-flex; align-items: center; gap: 10px; color: var(--navy-dark); font-size: 18px; font-weight: 700; text-decoration: none; }}
.brand img {{ width: 42px; height: 42px; object-fit: contain; border-radius: 8px; }}
.nav-links {{ display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }}
.nav-links a {{ color: var(--navy); padding: 8px 10px; text-decoration: none; border-radius: 6px; }}
.nav-links a:hover, .nav-links a:focus-visible {{ background: var(--accent-soft); outline: none; }}
.nav-toggle {{ display: none; width: 42px; height: 42px; border: 1px solid var(--line); border-radius: 8px; background: var(--white); padding: 9px; }}
.nav-toggle span:not(.sr-only) {{ display: block; height: 2px; margin: 5px 0; background: var(--navy); }}
.section {{ padding: 44px 0; }}
.section.white {{ background: var(--white); }}
.hero {{ padding-top: 42px; }}
.hero-card {{ display: grid; grid-template-columns: minmax(0, 1.4fr) minmax(280px, 0.9fr); gap: 28px; align-items: start; background: var(--hero-bg); border: 1px solid #dce8f1; border-radius: 8px; box-shadow: var(--shadow); padding: 32px 18px; }}
.eyebrow {{ margin: 0 0 8px; color: var(--accent); font-size: 13px; font-weight: 700; letter-spacing: 0.01em; text-transform: uppercase; }}
.eyebrow.blue {{ color: var(--accent); }}
h1, h2, h3, p {{ margin-top: 0; }}
h1 {{ margin-bottom: 8px; color: var(--navy-dark); font-size: clamp(34px, 5vw, 48px); line-height: 1.1; }}
h2 {{ margin-bottom: 8px; color: var(--navy-dark); font-size: clamp(26px, 4vw, 34px); line-height: 1.15; }}
h3 {{ margin-bottom: 8px; color: var(--navy); font-size: 19px; line-height: 1.25; }}
.hero h2 {{ color: var(--navy); font-size: clamp(22px, 3vw, 27px); }}
.lead, .section-subtitle {{ color: var(--muted); font-size: 16px; }}
.hero-actions {{ display: flex; flex-wrap: wrap; gap: 10px; margin-top: 18px; }}
.button {{ display: inline-flex; align-items: center; justify-content: center; min-height: 36px; padding: 8px 17px; border: 1px solid #d7e3f5; border-radius: 999px; font-weight: 700; text-decoration: none; }}
.button.primary {{ background: var(--navy); border-color: var(--navy); color: var(--white); }}
.button.secondary {{ background: var(--white); color: var(--navy); }}
.button.accent {{ background: var(--accent-soft); color: var(--navy-dark); border-color: var(--accent); }}
.hero-visual {{ display: grid; gap: 12px; justify-items: center; text-align: center; background: var(--white); border: 1px solid #e6edf7; border-radius: 8px; padding: 24px 18px; }}
.hero-visual img {{ width: 88px; height: 88px; object-fit: contain; border-radius: 8px; }}
.hero-visual div {{ border-radius: 8px; padding: 11px 14px; background: var(--accent-soft); color: var(--navy); font-weight: 700; }}
.two-column, .contribution-layout {{ display: grid; grid-template-columns: minmax(0, 1.25fr) minmax(280px, 0.75fr); gap: 24px; align-items: start; }}
.grid {{ display: grid; gap: 18px; margin-top: 20px; }}
.cards-four {{ grid-template-columns: repeat(4, minmax(0, 1fr)); }}
.cards-three {{ grid-template-columns: repeat(3, minmax(0, 1fr)); }}
.evidence-grid {{ grid-template-columns: repeat(3, minmax(0, 1fr)); }}
.card, .evidence-card, .certificate-card {{ min-width: 0; background: var(--white); border: 1px solid var(--line); border-radius: 8px; box-shadow: 0 12px 28px rgba(31,58,95,0.08); padding: 20px; }}
.card p:last-child, .evidence-card p:last-child, .certificate-card p:last-child {{ margin-bottom: 0; }}
.card-icon {{ color: var(--accent); font-size: 28px; font-weight: 700; line-height: 1; margin-bottom: 14px; }}
.reflection ul {{ margin: 12px 0 0; padding-left: 18px; color: var(--muted); }}
.note {{ padding: 12px; border-left: 4px solid var(--accent); background: var(--accent-soft); color: var(--navy-dark); }}
.video-card {{ display: grid; align-content: center; justify-items: center; text-align: center; min-height: 250px; background: var(--navy); color: #eaf2ff; border-radius: 8px; padding: 22px; }}
.video-card h3 {{ color: var(--white); }}
.play-icon {{ color: #ffffff; border: 1px solid rgba(255,255,255,0.45); border-radius: 999px; padding: 8px 14px; margin-bottom: 12px; font-weight: 700; }}
.evidence-card {{ padding: 0; overflow: hidden; }}
.evidence-card img {{ display: block; width: 100%; height: 170px; object-fit: cover; background: var(--accent-soft); }}
.evidence-card div {{ padding: 16px; }}
.certificate-card {{ display: flex; flex-direction: column; gap: 10px; }}
.certificate-card a {{ align-self: flex-start; color: var(--navy); font-weight: 700; text-decoration: none; border-bottom: 1px solid currentColor; }}
.pills {{ display: flex; flex-wrap: wrap; gap: 9px; margin: 18px 0 34px; }}
.pills span {{ color: var(--navy); background: #f8fbff; border: 1px solid #d7e3f5; border-radius: 999px; padding: 7px 12px; font-size: 13px; font-weight: 700; }}
.challenges-heading {{ margin-top: 16px; }}
.footer {{ background: var(--navy-dark); color: var(--white); padding: 34px 0; }}
.footer h2 {{ color: #ffffff; }}
.footer a {{ color: #ffffff; }}
@media (max-width: 960px) {{
  .hero-card, .two-column, .contribution-layout {{ grid-template-columns: 1fr; }}
  .cards-four, .cards-three, .evidence-grid {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
}}
@media (max-width: 720px) {{
  .nav {{ align-items: flex-start; flex-wrap: wrap; padding: 12px 0; }}
  .nav-toggle {{ display: inline-block; }}
  .nav-links {{ display: none; width: 100%; flex-direction: column; align-items: stretch; padding-top: 8px; }}
  .nav-links.open {{ display: flex; }}
  .nav-links a {{ padding: 10px 12px; }}
  .section {{ padding: 34px 0; }}
  .hero-card {{ padding: 24px 16px; }}
  .cards-four, .cards-three, .evidence-grid {{ grid-template-columns: 1fr; }}
}}
"""


def render_script() -> str:
    return """const navToggle = document.querySelector('.nav-toggle');
const navMenu = document.querySelector('#nav-menu');

if (navToggle && navMenu) {
  navToggle.addEventListener('click', () => {
    const isOpen = navMenu.classList.toggle('open');
    navToggle.setAttribute('aria-expanded', String(isOpen));
  });
}

async function loadJson(path) {
  const response = await fetch(path);
  if (!response.ok) return [];
  return response.json();
}

function renderEvidence(items) {
  const grid = document.querySelector('#evidence-grid');
  if (!grid) return;
  grid.innerHTML = items.map((item) => `
    <article class="evidence-card">
      <img src="${item.image}" alt="${item.title}">
      <div>
        <h3>${item.title}</h3>
        <p>${item.caption}</p>
      </div>
    </article>
  `).join('');
}

function renderCertificates(items) {
  const grid = document.querySelector('#certificate-grid');
  if (!grid) return;
  if (!items.length) {
    grid.innerHTML = '<article class="certificate-card"><h3>Certificate Section</h3><p>Certificate evidence section prepared for showcase review.</p></article>';
    return;
  }
  grid.innerHTML = items.map((item) => `
    <article class="certificate-card">
      <h3>${item.title}</h3>
      <p>Certificate evidence file.</p>
      <a href="${item.file}" target="_blank" rel="noopener">Open certificate</a>
    </article>
  `).join('');
}

loadJson('evidence.json').then(renderEvidence).catch(() => renderEvidence([]));
loadJson('certificates.json').then(renderCertificates).catch(() => renderCertificates([]));
"""


def render_redirect(portfolio: Portfolio) -> str:
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="0; url=site/">
    <title>{html.escape(portfolio.name)} Portfolio</title>
    <link rel="canonical" href="site/">
  </head>
  <body>
    <p><a href="site/">Open {html.escape(portfolio.name)} portfolio</a></p>
  </body>
</html>
"""


def write_readme(portfolio: Portfolio) -> None:
    contribution = portfolio.contribution
    owned = "\n".join(f"- `{item}`" for item in portfolio.owned_files) or "- Contribution evidence should be confirmed against the final group contribution record."
    text = f"""# {portfolio.name} - Computer Programming I Portfolio Showcase

## Overview
This repository contains {portfolio.name}'s static portfolio showcase for Computer Programming I.

## Live Site
The GitHub Pages URL will use the student's GitHub username and repository name after deployment.

## Project
Project: {portfolio.project}

## Student Contribution
{contribution}

## Tech Stack
- Static HTML, CSS, and JavaScript
- GitHub Pages
- GitHub Actions
- Preserved source materials where applicable

## Static Deployment Architecture
GitHub Pages serves the static site in `site/`. The Flet/Python source is preserved where applicable, but it is not used as the live GitHub Pages runtime.

## Local Preview
```bash
python -m http.server 8000 --directory site
```

Open:

```text
http://localhost:8000
```

## Evidence Assets
{owned}

The prepared evidence assets live in `site/assets/screenshots/`.

## Certificates
Certificate files, when available, live in `site/assets/certificates/` and are listed by `site/certificates.json`.

## Contribution Video Section
The static site includes an Individual Contribution Video section for the 1 minute 30 second showcase recording.

## GitHub Pages Deployment
GitHub Actions uploads the `site/` folder. Pages source must be GitHub Actions. Do not use branch/root deployment for Flet/Python.

## Maintenance Notes
- Keep private role documents out of Git.
- Keep tokens in local terminal environment variables only.
- Do not deploy the Flet/Python runtime to GitHub Pages.
"""
    write_text(portfolio.path / "README.md", text)


def ensure_gitignore(path: Path) -> None:
    additions = [
        "private-docs/",
        ".env",
        ".env.local",
        "*.token",
        "tokens.txt",
        "gittoken.txt",
        "token.txt",
        ".venv/",
        "__pycache__/",
        "**/__pycache__/",
        "build/",
        "dist/",
    ]
    existing = read_text(path / ".gitignore")
    lines = existing.splitlines()
    for item in additions:
        if item not in lines:
            lines.append(item)
    write_text(path / ".gitignore", "\n".join(lines).strip() + "\n")


def write_private_docs(portfolio: Portfolio) -> None:
    private_dir = portfolio.path / "private-docs"
    private_dir.mkdir(parents=True, exist_ok=True)
    role_text = f"""# Student Role Document

## Student Name
{portfolio.name}

## Project Name
{portfolio.project}

## Portfolio Purpose
This document supports the student's private preparation for the Computer Programming I portfolio showcase.

## Individual Role Summary
{portfolio.role}

Role details should be confirmed against the group's final contribution record.

## Technical Contribution
{portfolio.contribution}

## Collaboration Contribution
The student should describe communication, task tracking, review, and team handover work that they personally completed.

## Evidence To Capture
- Commit History Asset
- Development Branch Asset
- Pull Request Evidence Asset
- Interface Evidence Asset
- Code Contribution Asset
- Documentation Evidence Asset

## Suggested 1 Minute 30 Second Video Outline
- 0:00-0:15: Introduce name, project, and contribution area.
- 0:15-0:45: Show the main evidence asset or code area.
- 0:45-1:10: Explain a challenge and solution.
- 1:10-1:30: Summarise learning outcomes and final project value.

## Submission Checklist
- Static site opens locally.
- Evidence assets are present.
- Certificate section is reviewed.
- Video section is ready for the final link or upload.
- GitHub Pages workflow uploads `site/`.
- Tokens and private docs are not committed.
"""
    md = private_dir / "student-role-document.md"
    pdf = private_dir / "student-role-document.pdf"
    write_text(md, role_text)
    try:
        write_simple_pdf(pdf, "Student Role Document", role_text.splitlines())
    except Exception as exc:  # noqa: BLE001
        portfolio.warnings.append(f"PDF generation failed: {exc}")


def pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def write_simple_pdf(path: Path, title: str, lines: list[str]) -> None:
    content_lines = ["BT", "/F1 16 Tf", "72 760 Td", f"({pdf_escape(title)}) Tj", "/F1 10 Tf", "0 -24 Td"]
    line_count = 0
    for raw in lines:
        text = raw.strip()
        if not text:
            content_lines.append("0 -12 Td")
            continue
        for chunk in [text[i:i + 92] for i in range(0, len(text), 92)]:
            content_lines.append(f"({pdf_escape(chunk)}) Tj")
            content_lines.append("0 -14 Td")
            line_count += 1
            if line_count > 46:
                break
        if line_count > 46:
            break
    content_lines.append("ET")
    stream = "\n".join(content_lines).encode("latin-1", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for idx, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out.extend(f"{idx} 0 obj\n".encode())
        out.extend(obj)
        out.extend(b"\nendobj\n")
    xref_start = len(out)
    out.extend(f"xref\n0 {len(objects) + 1}\n".encode())
    out.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        out.extend(f"{offset:010d} 00000 n \n".encode())
    out.extend(f"trailer << /Root 1 0 R /Size {len(objects) + 1} >>\nstartxref\n{xref_start}\n%%EOF\n".encode())
    path.write_bytes(out)


def write_workflow(portfolio: Portfolio) -> None:
    write_text(portfolio.path / ".github" / "workflows" / "deploy-pages.yml", PAGES_WORKFLOW)


def prepare_portfolio(portfolio: Portfolio) -> None:
    write_site(portfolio)
    write_readme(portfolio)
    write_private_docs(portfolio)
    write_workflow(portfolio)
    ensure_gitignore(portfolio.path)
    portfolio.prepared = True


def validate_portfolio(portfolio: Portfolio) -> None:
    required = [
        "site/index.html",
        "site/styles.css",
        "site/script.js",
        ".github/workflows/deploy-pages.yml",
        "README.md",
        ".gitignore",
        "site/assets/icons/favicon.png",
    ]
    missing = [item for item in required if not (portfolio.path / item).exists()]
    evidence_missing = [
        filename for filename, _, _ in SITE_EVIDENCE
        if not (portfolio.path / "site" / "assets" / "screenshots" / filename).exists()
    ]
    public = read_text(portfolio.path / "site" / "index.html")
    forbidden = [
        pattern for pattern in FORBIDDEN_PUBLIC_PATTERNS
        if re.search(pattern, public, flags=0)
    ]
    py_compile = "not applicable"
    main_py = portfolio.path / "main.py"
    if main_py.exists():
        try:
            temp_pyc = BATCH_ROOT / "logs" / f"{portfolio.slug}.pyc"
            temp_pyc.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(
                [
                    "python",
                    "-c",
                    (
                        "import py_compile,sys;"
                        "py_compile.compile(sys.argv[1], cfile=sys.argv[2], doraise=True)"
                    ),
                    str(main_py),
                    str(temp_pyc),
                ],
                cwd=str(portfolio.path),
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=8,
            )
            temp_pyc.unlink(missing_ok=True)
            py_compile = "passed"
        except Exception as exc:  # noqa: BLE001
            temp_pyc.unlink(missing_ok=True)
            py_compile = f"failed: {exc}"
            portfolio.warnings.append(py_compile)
    portfolio.validation = {
        "missing": missing,
        "evidenceMissing": evidence_missing,
        "forbiddenPublicWording": forbidden,
        "favicon": (portfolio.path / "site" / "assets" / "icons" / "favicon.png").exists(),
        "pyCompile": py_compile,
        "valid": not missing and not evidence_missing and not forbidden and not str(py_compile).startswith("failed"),
    }


def write_deploy_scripts() -> None:
    scripts = BATCH_ROOT / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    write_text(scripts / "deploy-portfolio.ps1", DEPLOY_PS1)
    write_text(scripts / "deploy-all-from-config.ps1", DEPLOY_ALL_PS1)
    write_text(scripts / "deploy-portfolio.sh", DEPLOY_SH)
    write_text(scripts / "deploy-all-from-config.sh", DEPLOY_ALL_SH)
    write_text(scripts / "prepare-static-site.py", PREPARE_STATIC_SITE)
    write_text(scripts / "validate-portfolio.py", VALIDATE_PORTFOLIO)
    write_text(BATCH_ROOT / "workflow-templates" / "deploy-static-pages.yml", PAGES_WORKFLOW)


DEPLOY_PS1 = r'''param(
  [Parameter(Mandatory=$true)][string]$PortfolioPath,
  [Parameter(Mandatory=$true)][string]$StudentName,
  [Parameter(Mandatory=$true)][string]$GithubUsername,
  [Parameter(Mandatory=$true)][string]$StudentEmail,
  [Parameter(Mandatory=$true)][string]$RepoName,
  [Parameter(Mandatory=$true)][string]$TokenEnvironmentVariable,
  [string]$CommitMessage = "complete personal portfolio showcase",
  [switch]$Watch
)

$ErrorActionPreference = "Stop"

if (!(Test-Path -LiteralPath $PortfolioPath)) { throw "PortfolioPath does not exist." }
$resolved = (Resolve-Path -LiteralPath $PortfolioPath).Path
if (!(Test-Path -LiteralPath (Join-Path $resolved "site/index.html"))) { throw "site/index.html is missing." }
if (!(Get-Command git -ErrorAction SilentlyContinue)) { throw "git is required." }
if (!(Get-Command gh -ErrorAction SilentlyContinue)) { throw "GitHub CLI is required." }

$token = [Environment]::GetEnvironmentVariable($TokenEnvironmentVariable)
if ([string]::IsNullOrWhiteSpace($token)) {
  throw "Token environment variable is missing. Set it locally. Do not commit tokens."
}

$env:GH_TOKEN = $token
Push-Location $resolved
try {
  $ignore = ".gitignore"
  $protected = @("private-docs/", ".env", ".env.local", "*.token", "tokens.txt", "gittoken.txt", "token.txt")
  if (!(Test-Path $ignore)) { New-Item -ItemType File -Path $ignore | Out-Null }
  $existing = Get-Content $ignore -ErrorAction SilentlyContinue
  foreach ($line in $protected) {
    if ($existing -notcontains $line) { Add-Content -Path $ignore -Value $line }
  }

  if (!(Test-Path ".git")) { git init | Out-Null }
  git config user.name "$StudentName"
  git config user.email "$StudentEmail"
  git branch -M main
  git add .
  if ((git status --porcelain).Trim().Length -gt 0) {
    git commit -m "$CommitMessage"
  } else {
    Write-Host "No local changes to commit."
  }

  $repo = "$GithubUsername/$RepoName"
  gh repo view $repo *> $null
  if ($LASTEXITCODE -ne 0) {
    gh repo create $repo --public --source . --remote origin --push
  } else {
    git remote remove origin 2>$null
    git remote add origin "https://github.com/$repo.git"
    git push -u origin main
  }

  gh api --method POST "repos/$repo/pages" -f build_type=workflow 2>$null
  if ($LASTEXITCODE -ne 0) {
    gh api --method PUT "repos/$repo/pages" -f build_type=workflow
  }
  gh workflow run "Deploy Portfolio to GitHub Pages" --repo $repo --ref main
  if ($Watch) {
    gh run watch --repo $repo
    if ($LASTEXITCODE -ne 0) {
      gh run view --repo $repo --log-failed
      throw "Workflow failed. Review the failed log above."
    }
  }
  Write-Host "Expected live URL: https://$GithubUsername.github.io/$RepoName/"
} finally {
  Remove-Item Env:\GH_TOKEN -ErrorAction SilentlyContinue
  Pop-Location
}
'''


DEPLOY_ALL_PS1 = r'''param(
  [string]$ConfigPath = "portfolio-batch/deployment-config.local.json",
  [switch]$Watch
)

$ErrorActionPreference = "Stop"
if (!(Test-Path -LiteralPath $ConfigPath)) { throw "Config file not found: $ConfigPath" }
$items = Get-Content -Raw -LiteralPath $ConfigPath | ConvertFrom-Json
foreach ($item in $items) {
  & "$PSScriptRoot/deploy-portfolio.ps1" `
    -PortfolioPath $item.portfolioPath `
    -StudentName $item.studentName `
    -GithubUsername $item.githubUsername `
    -StudentEmail $item.studentEmail `
    -RepoName $item.repoName `
    -TokenEnvironmentVariable $item.tokenEnvironmentVariable `
    -Watch:$Watch
}
'''


DEPLOY_SH = r'''#!/usr/bin/env bash
set -euo pipefail

COMMIT_MESSAGE="complete personal portfolio showcase"
WATCH=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --portfolio-path) PORTFOLIO_PATH="$2"; shift 2 ;;
    --student-name) STUDENT_NAME="$2"; shift 2 ;;
    --github-username) GITHUB_USERNAME="$2"; shift 2 ;;
    --student-email) STUDENT_EMAIL="$2"; shift 2 ;;
    --repo-name) REPO_NAME="$2"; shift 2 ;;
    --token-env) TOKEN_ENV="$2"; shift 2 ;;
    --commit-message) COMMIT_MESSAGE="$2"; shift 2 ;;
    --watch) WATCH=1; shift ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

: "${PORTFOLIO_PATH:?Missing --portfolio-path}"
: "${STUDENT_NAME:?Missing --student-name}"
: "${GITHUB_USERNAME:?Missing --github-username}"
: "${STUDENT_EMAIL:?Missing --student-email}"
: "${REPO_NAME:?Missing --repo-name}"
: "${TOKEN_ENV:?Missing --token-env}"

[[ -d "$PORTFOLIO_PATH" ]] || { echo "PortfolioPath does not exist."; exit 1; }
[[ -f "$PORTFOLIO_PATH/site/index.html" ]] || { echo "site/index.html is missing."; exit 1; }
command -v git >/dev/null || { echo "git is required."; exit 1; }
command -v gh >/dev/null || { echo "GitHub CLI is required."; exit 1; }

TOKEN="${!TOKEN_ENV:-}"
if [[ -z "$TOKEN" ]]; then
  echo "Token environment variable is missing. Set it locally. Do not commit tokens."
  exit 1
fi

export GH_TOKEN="$TOKEN"
cd "$PORTFOLIO_PATH"
touch .gitignore
for line in "private-docs/" ".env" ".env.local" "*.token" "tokens.txt" "gittoken.txt" "token.txt"; do
  grep -qxF "$line" .gitignore || echo "$line" >> .gitignore
done

[[ -d .git ]] || git init
git config user.name "$STUDENT_NAME"
git config user.email "$STUDENT_EMAIL"
git branch -M main
git add .
if [[ -n "$(git status --porcelain)" ]]; then
  git commit -m "$COMMIT_MESSAGE"
else
  echo "No local changes to commit."
fi

REPO="$GITHUB_USERNAME/$REPO_NAME"
if gh repo view "$REPO" >/dev/null 2>&1; then
  git remote remove origin >/dev/null 2>&1 || true
  git remote add origin "https://github.com/$REPO.git"
  git push -u origin main
else
  gh repo create "$REPO" --public --source . --remote origin --push
fi

gh api --method POST "repos/$REPO/pages" -f build_type=workflow >/dev/null 2>&1 || \
  gh api --method PUT "repos/$REPO/pages" -f build_type=workflow
gh workflow run "Deploy Portfolio to GitHub Pages" --repo "$REPO" --ref main

if [[ "$WATCH" == "1" ]]; then
  if ! gh run watch --repo "$REPO"; then
    gh run view --repo "$REPO" --log-failed
    echo "Workflow failed. Review the failed log above."
    exit 1
  fi
fi

unset GH_TOKEN
echo "Expected live URL: https://$GITHUB_USERNAME.github.io/$REPO_NAME/"
'''


DEPLOY_ALL_SH = r'''#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="${1:-portfolio-batch/deployment-config.local.json}"
WATCH_ARG="${2:-}"
[[ -f "$CONFIG_PATH" ]] || { echo "Config file not found: $CONFIG_PATH"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python - "$CONFIG_PATH" "$WATCH_ARG" "$SCRIPT_DIR" <<'PY'
import json
import shlex
import subprocess
import sys
from pathlib import Path

config = json.loads(Path(sys.argv[1]).read_text())
watch = sys.argv[2] == "--watch"
script = Path(sys.argv[3]) / "deploy-portfolio.sh"
for item in config:
    cmd = [
        str(script),
        "--portfolio-path", item["portfolioPath"],
        "--student-name", item["studentName"],
        "--github-username", item["githubUsername"],
        "--student-email", item["studentEmail"],
        "--repo-name", item["repoName"],
        "--token-env", item["tokenEnvironmentVariable"],
    ]
    if watch:
        cmd.append("--watch")
    print("Running:", " ".join(shlex.quote(part) for part in cmd))
    subprocess.check_call(cmd)
PY
'''


PREPARE_STATIC_SITE = '''"""Regenerate static portfolio assets using scripts/generate_collab_portfolios.py."""
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parents[2]
subprocess.check_call(["python", str(root / "scripts" / "generate_collab_portfolios.py")], cwd=root)
'''


VALIDATE_PORTFOLIO = '''"""Quick validation for one prepared portfolio."""
import re
import sys
from pathlib import Path

path = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
required = ["site/index.html", "site/styles.css", "site/script.js", ".github/workflows/deploy-pages.yml", "README.md"]
missing = [item for item in required if not (path / item).exists()]
public = (path / "site/index.html").read_text(encoding="utf-8") if (path / "site/index.html").exists() else ""
forbidden = [p for p in [r"\\bReplace with\\b", r"\\bplaceholder\\b", r"\\bTODO\\b", r"\\bAI\\b", r"ChatGPT", r"will be added later", r"insert here", r"pending replacement"] if re.search(p, public)]
if missing or forbidden:
    print({"missing": missing, "forbidden": forbidden})
    raise SystemExit(1)
print("Portfolio validation passed.")
'''


def write_config_and_reports(portfolios: list[Portfolio]) -> None:
    BATCH_ROOT.mkdir(parents=True, exist_ok=True)
    (BATCH_ROOT / "logs").mkdir(parents=True, exist_ok=True)
    (BATCH_ROOT / "shared-assets").mkdir(parents=True, exist_ok=True)

    detected = []
    for p in portfolios:
        detected.append({
            "studentName": p.name,
            "folderPath": str(p.path),
            "detectedStack": p.stack,
            "hasGitRepo": (p.path / ".git").exists(),
            "hasAssets": (p.path / "assets").exists() or (p.path / "site" / "assets").exists(),
            "hasREADME": (p.path / "README.md").exists(),
            "hasGitHubActionsWorkflow": (p.path / ".github" / "workflows" / "deploy-pages.yml").exists(),
            "hasExistingContributionText": bool(p.contribution),
            "hasEvidenceScreenshots": bool(list((p.path / "site" / "assets" / "screenshots").glob("*.png"))),
            "hasVideoSection": "#video" in read_text(p.path / "site" / "index.html"),
            "hasPublicHelperWording": bool(p.validation.get("forbiddenPublicWording")),
            "deploymentReadiness": "ready" if p.validation.get("valid") else "warnings",
            "needsManualRoleConfirmation": p.needs_role_confirmation,
            "warnings": p.warnings + list(p.validation.get("missing", [])) + list(p.validation.get("forbiddenPublicWording", [])),
        })
    write_text(BATCH_ROOT / "detected-portfolios.json", json.dumps(detected, indent=2))

    with (BATCH_ROOT / "portfolio-batch-report.csv").open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=[
            "studentName", "folderPath", "detectedStack", "hasGitRepo", "hasAssets",
            "hasREADME", "hasGitHubActionsWorkflow", "hasExistingContributionText",
            "hasEvidenceScreenshots", "hasVideoSection", "hasPublicHelperWording",
            "deploymentReadiness", "needsManualRoleConfirmation", "warnings",
        ])
        writer.writeheader()
        writer.writerows(detected)

    site_spy_count = sum(1 for p in portfolios if not p.is_penny)
    prepared_count = sum(1 for p in portfolios if p.prepared)
    manual_count = sum(1 for p in portfolios if p.needs_role_confirmation)
    warning_count = sum(1 for p in portfolios if not p.validation.get("valid") or p.warnings)
    report = [
        "# Portfolio Batch Report",
        "",
        f"- SiteSpy portfolios discovered: {site_spy_count}",
        f"- Penny portfolio included: {'yes' if any(p.is_penny for p in portfolios) else 'no'}",
        f"- Portfolios prepared: {prepared_count}",
        f"- Need manual role confirmation: {manual_count}",
        f"- Validation warnings: {warning_count}",
        f"- Reference architecture checked: {REFERENCE_ROOT}",
        "",
        "## Portfolio Results",
        "",
        "| Student | Project | Stack | Prepared | Manual role confirmation | Validation |",
        "|---|---|---|---:|---:|---|",
    ]
    for p in portfolios:
        validation = "passed" if p.validation.get("valid") else "warnings"
        report.append(f"| {p.name} | {p.project} | {p.stack} | {p.prepared} | {p.needs_role_confirmation} | {validation} |")
    report.extend([
        "",
        "## Deployment Architecture",
        "",
        "All prepared portfolios use the static `site/` folder for GitHub Pages. Flet/Python source is preserved where present and is not used as the live Pages runtime.",
        "",
        "## Validation Scope",
        "",
        "Quick validation checked static files, workflow presence, evidence PNG files, favicon, public wording in `site/index.html`, and quick Python compilation where `main.py` exists.",
    ])
    write_text(BATCH_ROOT / "portfolio-batch-report.md", "\n".join(report) + "\n")

    log = {
        "siteSpyDiscovered": site_spy_count,
        "pennyIncluded": any(p.is_penny for p in portfolios),
        "prepared": prepared_count,
        "manualRoleConfirmation": manual_count,
        "validationWarnings": warning_count,
    }
    write_text(BATCH_ROOT / "logs" / "validation-summary.json", json.dumps(log, indent=2))

    config = [
        {
            "portfolioPath": str(p.path),
            "studentName": p.name,
            "githubUsername": p.github_username or "studentgithub",
            "studentEmail": p.email or "student@example.com",
            "repoName": p.repo_name,
            "tokenEnvironmentVariable": p.token_env,
        }
        for p in portfolios
    ]
    warning = "Do not commit real tokens. Set tokens in the terminal environment only."
    for item in config:
        item["warning"] = warning
    write_text(BATCH_ROOT / "deployment-config.example.json", json.dumps(config, indent=2))
    write_text(BATCH_ROOT / "deployment-config.local.json.example", json.dumps(config, indent=2))

    commands = ["# Deployment Commands", "", warning, ""]
    for p in portfolios:
        commands.extend([
            f"## {p.name}",
            "",
            "```powershell",
            (
                f'.\\portfolio-batch\\scripts\\deploy-portfolio.ps1 -PortfolioPath "{p.path}" '
                f'-StudentName "{p.name}" -GithubUsername "{p.github_username or "studentgithub"}" '
                f'-StudentEmail "{p.email or "student@example.com"}" -RepoName "{p.repo_name}" '
                f'-TokenEnvironmentVariable "{p.token_env}" -Watch'
            ),
            "```",
            "",
            "```bash",
            (
                f'./portfolio-batch/scripts/deploy-portfolio.sh --portfolio-path "{p.path}" '
                f'--student-name "{p.name}" --github-username "{p.github_username or "studentgithub"}" '
                f'--student-email "{p.email or "student@example.com"}" --repo-name "{p.repo_name}" '
                f'--token-env "{p.token_env}" --watch'
            ),
            "```",
            "",
        ])
    write_text(BATCH_ROOT / "deployment-commands.md", "\n".join(commands))


def main() -> None:
    portfolios = load_site_spy_portfolios()
    penny = load_penny_portfolio()
    if penny:
        portfolios.append(penny)
    for portfolio in portfolios:
        prepare_portfolio(portfolio)
        validate_portfolio(portfolio)
    write_deploy_scripts()
    write_config_and_reports(portfolios)
    print(json.dumps({
        "siteSpyPortfolios": sum(1 for p in portfolios if not p.is_penny),
        "pennyIncluded": bool(penny),
        "prepared": sum(1 for p in portfolios if p.prepared),
        "manualRoleConfirmation": sum(1 for p in portfolios if p.needs_role_confirmation),
        "warnings": sum(1 for p in portfolios if not p.validation.get("valid") or p.warnings),
        "batchRoot": str(BATCH_ROOT),
    }, indent=2))


if __name__ == "__main__":
    main()
